# This configuration file specifies the behavior of Gitpod workspaces for this project.

# 1. Define the tasks to be run when the workspace starts
tasks:
  - name: Setup Environment and Run App
    init: |
      echo "Starting Gitpod setup..."
      python -m venv venv
      source venv/bin/activate
      pip install fastapi uvicorn
      echo "Setup complete. App is ready to run."
    command: |
      source venv/bin/activate
      uvicorn main:app --reload --host 0.0.0.0 --port 8000

# 2. Expose the port where the Uvicorn server is running
ports:
  - port: 8000
    onOpen: open-browser